version: '3'
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.0.4
    networks:
      - mongo-cluster
    ports:
      - 27017:27017
    restart: always
    command: "--auth --keyFile /data/file.key --replSet rs0 --dbpath /data/db --journal --bind_ip_all"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "./scripts/file.key:/data/file.key"
      - "./data/mongo1:/data/db"
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.0.4
    networks:
      - mongo-cluster
    ports:
      - 27018:27017
    restart: always
    command: "--keyFile /data/file.key --replSet rs0 --dbpath /data/db --journal --bind_ip_all"
    volumes:
      - "./scripts/file.key:/data/file.key"
      - "./data/mongo2:/data/db"
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.0.4
    networks:
      - mongo-cluster
    ports:
      - 27019:27017
    restart: always
    command: "--keyFile /data/file.key --replSet rs0 --dbpath /data/db --journal --bind_ip_all"
    volumes:
      - "./scripts/file.key:/data/file.key"
      - "./data/mongo3:/data/db"
  mongo-replicator:
    build: ./mongo-replicator
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
networks:
  mongo-cluster:
    driver: bridge
